"""Add day-specific pricing columns to ScreenPricing

Revision ID: 166ff251265e
Revises: 887c0669f2bf
Create Date: 2025-09-04 14:53:07.048708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '166ff251265e'
down_revision = '887c0669f2bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('screen_pricing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_mon', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('price_tue', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('price_wed', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('price_thu', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('price_fri', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('price_sat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('price_sun', sa.Float(), nullable=True))
        batch_op.drop_column('price_per_thousand_contacts')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('screen_pricing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_per_thousand_contacts', sa.FLOAT(), nullable=False))
        batch_op.drop_column('price_sun')
        batch_op.drop_column('price_sat')
        batch_op.drop_column('price_fri')
        batch_op.drop_column('price_thu')
        batch_op.drop_column('price_wed')
        batch_op.drop_column('price_tue')
        batch_op.drop_column('price_mon')

    # ### end Alembic commands ###
