"""Swap price and contact fields in ScreenPricing

Revision ID: 6625c4fe8845
Revises: 166ff251265e
Create Date: 2025-09-05 15:19:51.178763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6625c4fe8845'
down_revision = '166ff251265e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('screen_pricing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('contacts_mon', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('contacts_tue', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('contacts_wed', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('contacts_thu', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('contacts_fri', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('contacts_sat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('contacts_sun', sa.Float(), nullable=True))
        batch_op.drop_column('price_tue')
        batch_op.drop_column('price_wed')
        batch_op.drop_column('contact_count')
        batch_op.drop_column('price_fri')
        batch_op.drop_column('price_sun')
        batch_op.drop_column('price_thu')
        batch_op.drop_column('price_mon')
        batch_op.drop_column('price_sat')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('screen_pricing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_sat', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('price_mon', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('price_thu', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('price_sun', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('price_fri', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('contact_count', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('price_wed', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('price_tue', sa.FLOAT(), nullable=True))
        batch_op.drop_column('contacts_sun')
        batch_op.drop_column('contacts_sat')
        batch_op.drop_column('contacts_fri')
        batch_op.drop_column('contacts_thu')
        batch_op.drop_column('contacts_wed')
        batch_op.drop_column('contacts_tue')
        batch_op.drop_column('contacts_mon')
        batch_op.drop_column('price')

    # ### end Alembic commands ###
