"""Add pixel_comment field to Screen model

Revision ID: 887c0669f2bf
Revises: 
Create Date: 2025-09-02 14:14:25.767571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '887c0669f2bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('screen', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pixel_comment', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('screen', schema=None) as batch_op:
        batch_op.drop_column('pixel_comment')

    # ### end Alembic commands ###
